### ISSUE TITLE
Strange command detection issue?

### ISSUE THREAD

**Issue by SupremeJUMBO** [kichikuou/vscode-system3x#2] opened 2024-03-17 01:36 UTC
Hello! I've recently started looking into other games besides KR, but encountered odd behavior when trying to use the program. If I'm in my KR folder, I can use the Decompile command with no issues. If I change folder to my Rance III folder, Decompile still works fine. But if I change to my Toushin Toshi folder, for some reason I get an error saying that 'there is no Decompile command'. I double-checked that the file path is correct for the SDK and xsys35 executable, tried restarting VSC, and restarting my computer. For some reason, when I change to the Toushin Toshi directory, it doesn't recognize Compile/Decompile commands. All 3 games are in folders located in the same location, so I don't see why there would be problems with just this specific folder. Could it be an issue with Toushin Toshi itself? Like the ain isn't compatible or something?

**Comment by SupremeJUMBO** [comment] 2024-03-17 01:38
![image](https://github.com/kichikuou/xsys35c/assets/156861343/afef2169-455c-43fd-bed7-4a3dd438af4a)

**Comment by kichikuou** [comment] 2024-03-17 02:43
In my environment, the OUTPUT tab shows `Error: there is no registered task type 'decompile'...` (which is a bug and I should fix it), but decompile of Toushin Toshi succeeds and source code is generated in the src folder.

I see `src` folder in your screenshot as well, but no source files are created in it?
Also, decompilation log is output to the TERMINAL tab. Is anything logged there?

**Comment by SupremeJUMBO** [comment] 2024-03-17 03:39
![image](https://github.com/kichikuou/vscode-system3x/assets/156861343/24ed67ba-4c33-49f4-a479-0feb80c275de)

**Comment by SupremeJUMBO** [comment] 2024-03-17 03:39
I've tried many times, but it never outputs any files into the src folder for me.

**Comment by kichikuou** [comment] 2024-03-17 04:03
> `Unexpected loop structure`

Ah okay, then this is a xsys35c issue, although I've transferred this issue to vscode-system3x as it looked like a VSCode extension issue. :smiley:

I was trying with Arunaru's translated version, but when I tried decompiling @RottenBlock's 1.5 patch I got the same error. Let me take a closer look.

**Comment by SupremeJUMBO** [comment] 2024-03-17 04:22
By the way, what's the best place for me to ask questions about how things work? I had some questions about System4/alice tools, but wasn't sure where to ask, so I posted on nunuhara's wall on the wiki. https://alicesoft.fandom.com/wiki/Message_Wall:%E3%83%8C%E3%83%8C%E3%83%8F%E3%83%A9

**Comment by kichikuou** [comment] 2024-03-17 05:03
> By the way, what's the best place for me to ask questions about how things work? I had some questions about System4/alice tools, but wasn't sure where to ask, so I posted on nunuhara's wall on the wiki. https://alicesoft.fandom.com/wiki/Message_Wall:%E3%83%8C%E3%83%8C%E3%83%8F%E3%83%A9

If you have questions about alice-tools, you should open an issue on https://github.com/nunuhara/alice-tools.

For general questions about how System4 works, I'm not sure there's a better place than the wiki.

**Comment by kichikuou** [comment] 2024-03-17 05:20
I looked into the cause of the error. It appears that there is actually a broken loop structure in the bytecode.

The `Unexpected loop structure` error was occurring when decompiling address 0xa62 of `END.SCO`. The following is the byte code for the relevant part of `END.SCO` (from `Toushin Toshi EN 1.5 Patch.zip`).

```
0xa51: 7b 41 7f 67 0a 00 00  # while-loop command('<@'), condition = '1' (loop forever), end-address = 0xa67
0xa62: 3e 1b 09 00 00        # loop-end command ('}'), loop-start-address = 0x91b
0xa67: EOF
```

When the decompiler encounters a loop-end command, it tries to find the start of the corresponding loop. However, since address 0x91b is not a start of any loop command, the decompiler fails to recover the loop structure.

This is the corresponding part of the Arunaru's version of `END.SCO`.

```
0x91b: 7b 41 7f 27 09 00 00  # while-loop command ('<@'), condition = '1' (loop forever), end-address = 0x927
0x922: 3e 1b 09 00 00        # loop-end command ('}'), loop-start-address = 0x91b
0x927: EOF
```

loop-start-address = 0x91b is the start address of the previous while-loop command.

It appears that @RottenBlock forgot to update the loop address of the `}` command from 0x91b to 0xa51 when they created the patch. I don't know how they did it, as this patch was created before the existence of xsys35c.

This can be a problem at runtime as well. The code is intended to cause an infinite loop (to halt the game) after the ending, but the 1.5 patch jumps to 0x91b at the end of the loop, possibly causing unexpected behavior.

**Comment by SupremeJUMBO** [comment] 2024-03-17 05:25
Ah ok, so it's not a decompiler problem then. Thanks for looking into it though! And the alice tools thing seems so obvious now lol. I saw that nunuhara makes commits to your stuff, and never thought to check their git account for the alice tools page.

**Closed as completed** 2024-03-17 05:49 UTC

**Comment by RottenBlock** [comment] 2024-03-17 08:38
Updated the patch. Funnily enough, I didn't actually create this error, though it's still my fault for not noticing such a weird block of code. It seems to have been created by Sys3Decompiler, which turns

```
	<@1:
	>
```

into

```
{ 1, lbl927:
> lbl91B:
*lbl927:
```

There is no lbl91B, thus the error.

I assume this means Sys3Decompiler will screw up every single <> loop. All the more reason to stick with xsys35 these days.

**Comment by SupremeJUMBO** [comment] 2024-03-17 08:55
That makes sense. When I made my KR mod, I used Sys3Decompiler for the first 2 versions. On the third version, I switched to xsys35, and my files would give compile errors when I tried to use them. Ended up remaking the mod from scratch lol.

**Comment by kichikuou** [comment] 2024-03-17 23:05
Confirmed that the decompiler works for the 1.51 patch. Thanks for the fix @RottenBlock!
